Ea 907 sample android app integrate with 1.0.0 snapshot
icanbwell/bwell-sdk-example pull request #18
Opened 2023-12-27 05:47 UTC by Arunkumarbwell

2023-12-28 03:59 UTC, grantespo requested changes

2023-12-28 03:59 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/data_connections/DataConnectionsFragment.kt
> +                            if (connectionOutcome.status != Status.SUCCESS) {
remove empty if condition

2023-12-28 03:59 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/healthsummary/HealthSummaryFragment.kt
> +                    .page(1)
for these request builders, `page` is already 0 by default, so it's not necessary to specify `.page(1)` in the builder because this is actually the 2nd page

2023-12-28 03:59 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/home/HomeFragment.kt
> +                clientKey = "eyJyIjoiMTVoaGcwOHpybjgyOW8zenV3ZHgiLCJlbnYiOiJkZXYiLCJraWQiOiJzYW1zdW5nLWRldiJ9",
we probably don't want to hardcode this here

2023-12-28 20:20 UTC, grantespo approved these changes

2023-12-29 18:50 UTC, wootencl commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/home/HomeFragment.kt
> +            ))
Should there be multiple `initialize` calls? Is it not possible to initialize once and share it as a singleton?

2023-12-29 21:48 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/home/HomeFragment.kt
> +            ))
it appears there are 2 initialize calls (not sure why)

one in MainActivity and one in HomeFragment

I just tried removing the initialize call in HomeFragment and keeping the one in MainActivity but that caused buggy behavior.

For now, I removed the duplicate initialize call in MainActivity and kept the one here in HomeFragment (which seems to be ok)

2023-12-29 22:02 UTC, wootencl commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/home/HomeFragment.kt
> +            ))
Weird. If everything is working then something we can revisit later 🤷‍♂️

2023-12-29 22:02 UTC, wootencl approved these changes

2023-12-29 22:05 UTC, merged