EA-779-sample-android-app-profile-getProfile-updateProfile
icanbwell/bwell-sdk-example pull request #5
Opened 2023-11-08 17:47 UTC by Arunkumarbwell

2023-11-08 18:22 UTC, grantespo commented
left a couple of comments.

Also, for`fragment_edit_profile.xml`

- should we also include the "Why Do We Ask This" label from [this ticket](https://icanbwell.atlassian.net/browse/EA-779)?
- The Zip Code and State TextViews should probably have equal heights.

2023-11-08 18:25 UTC, grantespo approved these changes
left a couple of comments.

Also, for `fragment_edit_profile.xml`

 - should we also include the "Why Do We Ask This" label from [this ticket](https://icanbwell.atlassian.net/browse/EA-779)?
 - The Zip Code and State TextViews should probably have equal heights.

2023-11-08 18:25 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/profile/ProfileFragment.kt
We probably shouldn't hardcode the mock data directly into the variables like this, 

It might be better to store the data in a mock profile class and initialize the variables from that mock profile class.

2023-11-08 18:25 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/profile/ProfileFragment.kt
> +                binding.includeViewProfile.textViewSexData.text= it.gender
maybe change `it.gender` to `it.sexAssignedAtBirth`?

2023-11-08 18:25 UTC, grantespo commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/profile/ProfileViewModel.kt
> +            TODO("VERSION.SDK_INT < O")
should this TODO be resolved in this PR?

2023-11-08 18:27 UTC, grantespo commented
Also if the user pushes enter on the textview or presses the enter key, it shouldn't create a new line for each textview.

It should probably close the keyboard.

2023-11-08 18:37 UTC, grantespo commented
Autocapitalization should be enabled for the first name, last name, address, and city fields.

 Zip Code should probably be a numerical textfield

2023-11-09 15:27 UTC, istashak requested changes

2023-11-09 15:27 UTC, istashak commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/repository/Repository.kt
> +        if(BWellSdk.user?.getProfile()?.operationOutcome?.status==Status.SUCCESS){
I think the results of BWellSdk.user?.getProfile() should be saved to a variable to avoid calling it twice.

2023-11-09 16:24 UTC, Arunkumarbwell commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/profile/ProfileFragment.kt
> +                binding.includeViewProfile.textViewSexData.text= it.gender
its is coming from SDK method's Person object.

2023-11-09 21:18 UTC, istashak approved these changes

2023-11-10 03:17 UTC, merged