Ea 757 sample  data connection data from mock sdk-ProviderSearchRequest-searchConnections-searchProviders
icanbwell/bwell-sdk-example pull request #8
Opened 2023-11-28 14:03 UTC by Arunkumarbwell

Updated SDK version 0.3.0,integrated Data connection flow :- ProviderSearchRequest(),searchConnections(),searchProviders()

2023-11-30 16:05 UTC, istashak commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/activities/ui/data_connections/DataConnectionsFragment.kt
> +                viewLifecycleOwner.lifecycleScope.launch {
I noticed that clicking "Disconnect" on the Lab connection doesn't do anything. I'd expect it to either disappear or change from Connected to Disconnected.

I'm not sure if this was part of the acceptance criteria, if not ignore this comment.

2023-11-30 16:36 UTC, istashak commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/utils/SelectedOrganizationHolder.kt
> +}
This is an error prone way of holding the selectedOrganization.

I'd do this to the Fragment constructors that require it instead:

class OrganizationInfoFragment constructor(organization: ProviderSearchQuery.Organization) : Fragment() ...

2023-12-01 14:19 UTC, Arunkumarbwell commented on bwell-kotlin-android/app/build.gradle.kts
> +    implementation("com.apollographql.apollo3:apollo-api:3.8.2")
Yes tried to remove this but getting issue

2023-12-01 16:30 UTC, Arunkumarbwell commented on bwell-kotlin-android/app/build.gradle.kts
> +    implementation("com.apollographql.apollo3:apollo-api:3.8.2")
Done

2023-12-01 16:30 UTC, Arunkumarbwell commented on bwell-kotlin-android/app/src/main/java/com/bwell/sampleapp/utils/SelectedOrganizationHolder.kt
> +}
Done

2023-12-01 16:38 UTC, istashak approved these changes

2023-12-01 17:42 UTC, wfieldx requested changes
make sure you're not checking in things that aren't to be checked in. e.g. local properties:

```
-## This file must *NOT* be checked into Version Control Systems,
-# as it contains information specific to your local configuration.
-#
-# Location of the SDK. This is only used by Gradle.
-# For customization when using a Version Control System, please read the
-# header note.
-#Thu Nov 02 03:15:32 GMT 2023
-sdk.dir=/Users/arunkumar/Library/Android/sdk
```

2023-12-01 17:58 UTC, wfieldx requested changes
1. User's name should be displayed here: Welcome!!BWell
2. navigation around data connections is incorrect (i.e. no back out of search, you have to select something other than "data connections"  from the side bar and go through it again)

2023-12-04 08:24 UTC, Arunkumarbwell commented
> 1. User's name should be displayed here: Welcome!!BWell
> 2. navigation around data connections is incorrect (i.e. no back out of search, you have to select something other than "data connections"  from the side bar and go through it again)

Done

2023-12-18 17:20 UTC, wfieldx approved these changes

2023-12-18 17:28 UTC, merged